version: '3.2'

services:
   db:
     image: postgres:13
     volumes:
       - db:/var/lib/postgresql/data/pgdata
     restart: always
     environment:
       POSTGRES_PASSWORD: odoo
       POSTGRES_DB: postgres
       POSTGRES_USER: odoo
       PGDATA: /var/lib/postgresql/data/pgdata

   odoo:
     depends_on:
       - db
     image: odoo:14
     volumes:
      - data:/var/lib/odoo
      - extra-addons:/mnt/extra-addons
     ports:
       - 8069:8069
     restart: always
     environment:
       HOST: db
       USER: odoo
       PASSWORD: odoo
volumes:
    db_data:
    data: 
    extra-addons:
